### PR TITLE
Give shirt-bot environment variable support.

### PR DESCRIPTION
**Pull request by jozz024**
replaced the need for a config.json with a .env, supplied a sample .env and modified readme to reflect changes.

### CODE REVIEW

**Comment by ghost** [comment]
Why is this preferable to the current approach? [python-dotenv](https://pypi.org/project/python-dotenv/) is not a part of the standard library, so this would just make an extra dependency that needs to be installed.

**Comment by jozz024** [comment]
> Why is this preferable to the current approach? [python-dotenv](https://pypi.org/project/python-dotenv/) is not a part of the standard library, so this would just make an extra dependency that needs to be installed.

it would be useful for people who don't want a config file, they can just add the various entries to their environment, it's also useful for the various hosting spaces that treat .env files as "secret" files, an example being [replit](https://replit.com).

**Comment by ghost** [comment]
> it would be useful for people who don't want a config file, they can just add the various entries to their environment

This implementation behaves exactly like a config file. It doesn't work without the dotenv module, which is used to load the configuration.

> it's also useful for the various hosting spaces that treat .env files as "secret" files, an example being [replit](https://replit.com).

[This has been deprecated in replit](https://docs.replit.com/archive/secret-keys) (first paragraph).
<br>
It would be cool to, however, add a feature to default to environment variables if a key in the config is set to an empty string, though it would expect you to handle your own variables, since I don't want to add an extra dependency. This wouldn't be a problem for your example, [replit](https://replit.com), since it has a UI for setting environment variables. This also wouldn't break any existing users' configurations so they won't have to update if they're already using the config file regularly.

**Comment by jozz024** [comment]
to clarify the repl thing, if you import a .env into repl it will automatically add everything in the .env into its secrets. also, this implementation should load anything in your environment (not in .env, because iirc if dotenv can't find a .env file or something in the .env file it will just go straight to your environment variables) that has the matching name, i can test that when i get home tonight though.

**Comment by jozz024** [comment]
also yeah, a dual implementation of both the config file and environment would be nice, i have an idea as to how to do that so i'll work on it when i get home.

**Comment by ghost** [comment]
My idea was to just do it like this:
Original:
`API_KEY = config["api_key"]`

New:
`API_KEY = config["api_key"] if config["api_key"] else os.getenv("api_key")`

Since an empty string is falsy, leaving it blank would cause it to just default to using the environment variable.

**Comment by jozz024** [comment]
yeah that was my idea too, i'll implement it when i get home and see if i can make this pull request reflect those changes, otherwise i'll close this one and make a new one

**Comment by ghost** [comment]
Hello. Have you worked on implementing this so I know whether to close this yet or not?

**Comment by jozz024** [comment]
oh i'm super sorry, have been busy for a good portion of the past few days so i haven't had time to implement it, it should be done by end of day.

**Comment by ghost** [comment]
Also, it would be better to use `config.get("api_key", os.getenv("api_key"))` instead of `config["api_key"] if config["api_key"] else os.getenv("api_key")` since it doesn't require a ternary operator and actually uses the builtin way of doing this.

**Comment by jozz024** [comment]
this should be it, all i have left to do is re-add the config.json.template and update readme.md

**Comment by jozz024** [comment]
this should be the last commit, unless i need to fix something that gets pointed out later.

**Comment by ghost** [comment]
I was under the impression that we'd have environment defaults only in case the config entry didn't exist, not in the case it's blank, but I guess this may be more explicit and thus okay. I'll accept it on the next day when I take a better look at the changes. Thank you!

**Comment by jozz024** [comment]
oh it may work when config entry doesn't exist, i had not tested that. i'll test it right now and tell you the result.

**Comment by jozz024** [comment]
ah yea it does not work if the config entry doesn't exist, but yea it does seem more explicit which will probably be better.

**Comment by ghost** [comment]
Can you squash these into a single commit? I'll merge it afterward.

**Comment by jozz024** [comment]
yep, just give me a couple hours and i'll squash the commits for ya

**Comment by jozz024** [comment]
the commits have been squashed

**Comment by ghost** [comment]
I'll make some style changes and update the readme to give more information. Is leaving .env inside of the gitignore a mistake or was it intended? I'll remove it for now.

**Comment by jozz024** [comment]
ah yea leaving .env was a mistake

**Comment by ghost** [comment]
Alright, thank you for the PR!

**Pull request merged**
